### ISSUE TITLE
Package for Ubuntu 20.04 not found

### ISSUE THREAD

**Issue by hellocatfood** [muflone/gespeaker#68]
Since Ubuntu 20.04 Gespeaker is no longer in the repositories. Can it be packaged for this or future versions?

**Comment by gnat** [comment]
Would be nice to get this updated for 20.04

**Comment by amquei** [comment]
I want this too, please.

**Comment by Stemby** [comment]
Same thing on Debian.

I think the first step is migrating from Python 2 to Python 3.

**Comment by MoonDragon-MD** [comment]
I also had this problem but I solved it this way:
1) Download [https://packages.debian.org/buster/amd64/python-glade2/download](url) and [https://packages.debian.org/buster/amd64/python-gtk2/download](url) and [https://github.com/muflone/gespeaker/releases/download/0.8.6/gespeaker_0.8.6-1_all.deb](url)
2) open term and
`sudo dpkg -i python-gtk2_2.24.0-5.1+b1_amd64.deb
sudo apt --fix-broken install
sudo dpkg -i python-glade2_2.24.0-5.1+b1_amd64.deb
sudo dpkg -i gespeaker_0.8.6-1_all.deb    
sudo apt --fix-broken install   `
3) Ready to go ;)

**Comment by adeptflax** [comment]
@MoonDragon-MD thanks works, but I had to deal with installing dbus-python.

**Comment by arifmahmudrana** [comment]
> I also had this problem but I solved it this way:
> 
> 1. Download [https://packages.debian.org/buster/amd64/python-glade2/download](url) and [https://packages.debian.org/buster/amd64/python-gtk2/download](url) and [https://github.com/muflone/gespeaker/releases/download/0.8.6/gespeaker_0.8.6-1_all.deb](url)
> 2. open term and
>    `sudo dpkg -i python-gtk2_2.24.0-5.1+b1_amd64.deb`
>    `sudo apt --fix-broken install`
>    `sudo dpkg -i python-glade2_2.24.0-5.1+b1_amd64.deb`
>    `sudo dpkg -i gespeaker_0.8.6-1_all.deb `
>    `sudo apt --fix-broken install   `
> 3. Ready to go ;)

Didn't work for me

**Comment by arifmahmudrana** [comment]
This project seems to be stalled so I use like this

1. Install `xsel` by running `sudo apt install xsel -y` (if `espeak` not installed the add `espeak` with `xsel`)
2. Create a shortcut `System Settings > Keyboard > Shortcuts > + `.
3. Then add this command in shortcut `bash -c "espeak \"$(xsel | sed -e :a -e '$!N;s/\n/ /;ta')\""`
4. Then give a shortcut e.g. `Super + R`

Now when you select a text and press `Super + R` the text selected will be read
![image](https://user-images.githubusercontent.com/2046796/122863228-3bd53f00-d344-11eb-8f22-ad004bcb27f9.png)

**Comment by gnat** [comment]
Nice one @arifmahmudrana 

I also bind `bash -c "killall espeak"` to `Shift-Super-R` to make espeak stop talking.

**Comment by laveruberlue** [comment]
hello I am new in learning code, i'd really like to install gespeaker for me to work with. Is it possible for you to describe in details all the code lines I must put in my terminal to be able to work with gespeaker, and learning more about coding as well.
thanx

**Comment by arifmahmudrana** [comment]
> hello I am new in learning code, i'd really like to install gespeaker for me to work with. Is it possible for you to describe in details all the code lines I must put in my terminal to be able to work with gespeaker, and learning more about coding as well.
> thanx

@laveruberlue you can't I guess for Ubuntu 20 version and my https://github.com/muflone/gespeaker/issues/68#issuecomment-865518546 and https://github.com/muflone/gespeaker/issues/68#issuecomment-869719804 should be enough.

gespeaker is a GUI for espeak. I use to use Jovie but as that's also deprecated you can use our methods for text to speech using this shortcuts I guess.

**Comment by gnat** [comment]
Since we're on the verge of a new 22.04 LTS, I thought I'd share my favorite settings for this keyboard shortcut.

for **espeak** `bash -c "espeak -s260 -g0 -p40 -v english-us \"$(xsel | sed -e :a -e '$!N;s/\n/ /;ta')\""`
for **espeak-ng** `bash -c "espeak-ng -s260 -g0 -p40 -v en-us \"$(xsel | sed -e :a -e '$!N;s/\n/ /;ta')\""`

* American voice, lower pitch.
* No delays.
* Higher speed.

@laveruberlue https://github.com/muflone/gespeaker/issues/68#issuecomment-865518546 is all you need. Works in Ubuntu 22.04
