### ISSUE TITLE
Python 2 to 3 migration

### ISSUE THREAD

**Issue by jgreen01** [muflone/gespeaker#69]
Hi I'd like to help migrate this project from Python 2 to 3.

How can I help? What do we need to do?

**Comment by joseantoniosa** [comment]
I'm only an user. I've found this URL:
[Python 2 to python3 guide ](https://www.digitalocean.com/community/tutorials/how-to-port-python-2-code-to-python-3)
I hope it will be useful 
Thanks a lot!

**Comment by jgreen01** [comment]
It appears the developers have abandoned this project.

@joseantoniosa what do you think of this project is worth supporting? Do you still use it or have you found another piece of software for text to speech?

**Comment by joseantoniosa** [comment]
> It appears the developers have abandoned this project.
@jgreen01 I don't really know if this application was abandoned, last commit from November.
> 
> @joseantoniosa what do you think of this project? Is it worth supporting?
I don't know, I was unable to run this core (I can't install python2 dependencies: python-gi ) . It seems interesting.
> Do you still use it or have you found another piece of software for text to speech?
I use "Read Aloud" Firefox plugin. But it's no free software.
I'm looking for an program for desktop to read text aloud, or a Calibre (software to read e-books) plugin.

**Comment by jgreen01** [comment]
> > It appears the developers have abandoned this project.

> @jgreen01 I don't really know if this application was abandoned, last commit from November.

Weird.. You'd think any maintainer would jump at the chance to have a little help. @muflone? @zonksoft?

> > @joseantoniosa what do you think of this project? Is it worth supporting?

> I don't know, I was unable to run this core (I can't install python2 dependencies: python-gi ) . It seems interesting.

Yeah I've always wanted to hack on this project.

> > Do you still use it or have you found another piece of software for text to speech?

> I use "Read Aloud" Firefox plugin. But it's no free software.
> I'm looking for an program for desktop to read text aloud, or a Calibre (software to read e-books) plugin.

This was my favorite reader for Linux. I used it all the time in college. I didn't know if something else came and took this ones place. I haven't used Linux much since I graduated.

**Comment by joseantoniosa** [comment]
> Weird.. You'd think any maintainer would jump at the chance to have a little help. @muflone? @zonksoft?
Sure! Or just fork it :-) 
> 
> 
> Yeah I've always wanted to hack on this project.
Are you a python programmer? Give gespeaker  a try! (It has 2027 lines of python  code)
> 
> > > Do you still use it or have you found another piece of software for text to speech?
> 
> > I use "Read Aloud" Firefox plugin. But it's no free software.
> > I'm looking for an program for desktop to read text aloud, or a Calibre (software to read e-books) plugin.
> 
> This was my favorite reader for Linux. I used it all the time in college. I didn't know if something else came and took this ones place. I haven't used Linux much since I graduated.

Nice!

**Comment by jgreen01** [comment]
I'm not a Python developer but I've used it a few times. 2000 lines doesn't sounds too bad. Maybe I could fork it.

**Comment by muflone** [comment]
There's a GTK 3 Python 3 branch since many years but I never managed it to complete for lack of time

Please test that one

**Comment by jgreen01** [comment]
Great! I'll pull it and see what I can do.

**Comment by HumanG33k** [comment]
Some news about Python 3 + GTK 3 ? 

I identify : 

gespeaker : Dépend: python-glade2 which is a virtual package and is not provided by any available package

             Dépend: python-gobject which is a virtual package and is not provided by any available package

             Dépend: python-gtk2 which is a virtual package and is not provided by any available package

             Dépend: python-xdg which is a virtual package and is not provided by any available package

             Dépend: python:any (>= 2.7.5-5~) which is a virtual package, provided by:
                      - python-is-python2 (2.7.18-9) provides python:any=2.7.18-2, but it is not going to be installed

On current debian testing. 

Can i help to do something ?

**Comment by zonksoft** [comment]
Are people still interested in this? I'm not actively involved (I fixed one bug once a number of years ago) but if you can convince me in two sentences, I will look into it.

**Comment by muflone** [comment]
The source code in the main master was already ported to Python 3 + GTK 3

Test it if you want to help
