### ISSUE TITLE
No module named 'gespeaker'

### ISSUE THREAD

**Issue by vvasuki** [muflone/gespeaker#74]
On an arch linux computer (installed `gespeaker-git-2.0.1-1` from the standard repository), I get the below:

```
Traceback (most recent call last):
  File "/usr/bin/gespeaker", line 28, in <module>
    from gespeaker.settings import Settings                            # noqa: E402
ModuleNotFoundError: No module named 'gespeaker'

```

What could be the problem?

**Comment by muflone** [comment]
When do you have installed gespeaker-git ?
If the package was installed before the python package was updated then you have to rebuild and reinstall it again

**Comment by vvasuki** [comment]
Thanks! The following worked (reinstallation after cleaning cache):

```
yay -Sc
yay -S gespeaker-git
```
