### ISSUE TITLE
Is the project still alive?

### ISSUE THREAD

**Issue by ZeroDot1** [muflone/gespeaker#76]
To me, it looks like this project is also a dead end, like so many good projects.
Very sad, the settings are still not implemented and the program crashes with long texts. and some new voices e.g. from Google can not be loaded.

**Comment by muflone** [comment]
Unfortunately my days are always too much busy but if you have some issues with Gespeaker 2.x please describe them better to try to solve them

**Comment by gnat** [comment]
For those interested in an alternative, I made a Qt6 GUI alternative: https://github.com/gnat/text-to-speech-ubuntu
